# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160105003935 on 2016-01-23 04:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='book name')),
                ('isbn', models.CharField(max_length=200, verbose_name='isbn')),
                ('authors', models.CharField(max_length=200, verbose_name='author')),
                ('pub_date', models.DateField(verbose_name='data published')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date reviewed')),
                ('like', models.SmallIntegerField(verbose_name='like')),
                ('comment', models.CharField(max_length=1000, verbose_name='comment')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookreview.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
